baseurl = "https://www.jonrei.de"
title = "jonrei"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
    author = "Jonas Reineke"
    info = "DevOps Engineer"
    description = "Jonas Reineke's personal website"
    keywords = "personal"
    avatarurl = "images/avatar.jpg"

    favicon_32 = "images/favicon-32x32.png"
    favicon_16 = "images/favicon-16x16.png"

    footercontent = ""

    hidecredits = false
    hidecopyright = false

    rtl = false

    math = false

    colorscheme = "dark"

# Social links
[[params.social]]
    name = "Github"
    icon = "fa-github fa-2x"
    weight = 1
    url = "https://github.com/jon-rei/"
[[params.social]]
    name = "DockerHub"
    icon = "fa-docker fa-2x"
    weight = 2
    url = "https://hub.docker.com/u/jonreide"
[[params.social]]
    name = "LinkedIn"
    icon = "fa-linkedin fa-2x"
    weight = 3
    url = "https://www.linkedin.com/in/jonas-reineke/"
[[params.social]]
    name = "Xing"
    icon = "fa-xing fa-2x"
    weight = 4
    url = "https://www.xing.com/profile/Jonas_Reineke2"