on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          submodules: true
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3.0.0
        with:
          hugo-version: "latest"
      - name: Build site with Hugo
        run: hugo --minify
      - name: rsync deployments
        uses: burnett01/rsync-deployments@7.0.2
        with:
          switches: -avzr --delete
          path: /public/
          remote_path: /var/www/virtual/${{ secrets.RSYNC_USER }}/hugo/public
          remote_host: ${{ secrets.RSYNC_HOST }}
          remote_user: ${{ secrets.RSYNC_USER }}
          remote_key: ${{ secrets.RSYNC_DEPLOY_KEY }}
